name: comprobar calidad con script suma

on: push 

jobs:
  linter:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
    
    steps:
      - name: cargar codigo
        uses: actions/checkout@v5

      - name: instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: comprobar calidad
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

  
